"""Reference solution as an ordered chain of per-requirement scripts.

    task/solution/
    ├── solve.sh        # orchestrator: runs the steps below in order, stops at the first failure
    ├── solve_R1.sh     # atomic change for requirement R1
    └── solve_R3.sh     # atomic change for requirement R3 (R2 was an invariant: no step)

Why a chain instead of one script: when the healing round rewrites the fix for R3 it must not
be able to "forget" R1 and R2. Steps of requirements that already converged are frozen (the
pipeline rejects a healed bundle that changes them) and a requirement that never converges is
pruned from the bundle as a whole - its step, its tests, its paragraph in instruction.md -
instead of dragging the whole case down.
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Iterable

from harness.providers.python.env_builder import write_lf

_RID = re.compile(r"^R(\d+)$")
STEP_MARKER = "[solve] step "          # printed by the orchestrator before each step (see solve.log)


def requirement_order(rid: str) -> int:
    m = _RID.match(rid)
    return int(m.group(1)) if m else 10**6


def step_file(rid: str) -> str:
    return f"solve_{rid}.sh"


@dataclass
class StagedSolution:
    steps: dict[str, str] = field(default_factory=dict)      # requirement id -> POSIX sh script
    pruned: dict[str, str] = field(default_factory=dict)     # requirement id -> reason

    # ---------------------------------------------------------------- building
    @classmethod
    def from_items(cls, items: Iterable[dict[str, Any]]) -> tuple["StagedSolution", list[str]]:
        """Parse `solve_steps` from a model bundle. Returns (solution, problems)."""
        problems: list[str] = []
        steps: dict[str, str] = {}
        for i, item in enumerate(items, 1):
            if not isinstance(item, dict):
                problems.append(f"solve_steps[{i}] is not an object")
                continue
            rid = str(item.get("requirement_id", "")).strip()
            script = item.get("script")
            if not _RID.match(rid):
                problems.append(f"solve_steps[{i}]: requirement_id {rid!r} must look like R1, R2, ...")
                continue
            if rid in steps:
                problems.append(f"solve_steps: requirement {rid} has two steps")
                continue
            if not isinstance(script, str) or not script.strip():
                problems.append(f"solve_steps: script for {rid} is empty")
                continue
            if "/tests" in script:
                problems.append(f"solve_steps: script for {rid} must not reference /tests")
            steps[rid] = _normalise(script)
        ordered = dict(sorted(steps.items(), key=lambda kv: requirement_order(kv[0])))
        return cls(steps=ordered), problems

    @property
    def order(self) -> list[str]:
        return sorted(self.steps, key=requirement_order)

    def prefix(self, upto: str) -> "StagedSolution":
        """Steps R1..upto (inclusive) - used by the staged diagnostic runs."""
        keep = [r for r in self.order if requirement_order(r) <= requirement_order(upto)]
        return StagedSolution(steps={r: self.steps[r] for r in keep})

    def prune(self, rid: str, reason: str) -> bool:
        """Drop the step of `rid`; returns False when there was nothing to drop."""
        self.pruned[rid] = reason
        return self.steps.pop(rid, None) is not None

    def changed_steps(self, other: "StagedSolution") -> list[str]:
        """Requirement ids whose script differs between self and `other` (added/removed count too)."""
        ids = set(self.steps) | set(other.steps)
        return sorted((r for r in ids if self.steps.get(r, "").strip() != other.steps.get(r, "").strip()),
                      key=requirement_order)

    # --------------------------------------------------------------- rendering
    def orchestrator(self) -> str:
        """solve.sh: runs every step from the directory it lives in (works both as
        `sh /solution/solve.sh` in the sandbox and from a host checkout in tests)."""
        lines = ["#!/bin/sh", "# Generated by benchmark-harness: reference solution as a chain of per-requirement steps.",
                 "set -eu", 'here=$(cd "$(dirname "$0")" && pwd)']
        for rid in self.order:
            lines += [f'echo "{STEP_MARKER}{rid}"', f'sh "$here/{step_file(rid)}"']
        lines.append('echo "[solve] done"')
        return "\n".join(lines) + "\n"

    def combined(self) -> str:
        """Single-script view of the chain (for prompts, diffs and evidence)."""
        parts = [f"# ---- {rid} ({step_file(rid)})\n{self.steps[rid]}" for rid in self.order]
        return "#!/bin/sh\nset -eu\n" + "\n".join(parts)

    def write(self, solution_dir: Path) -> None:
        solution_dir.mkdir(parents=True, exist_ok=True)
        for old in solution_dir.glob("solve*.sh"):
            old.unlink()
        for rid in self.order:
            write_lf(solution_dir / step_file(rid), self.steps[rid])
        write_lf(solution_dir / "solve.sh", self.orchestrator())

    def to_items(self) -> list[dict[str, str]]:
        return [{"requirement_id": rid, "script": self.steps[rid]} for rid in self.order]


def _normalise(script: str) -> str:
    text = script.replace("\r\n", "\n")
    if not text.startswith("#!"):
        text = "#!/bin/sh\nset -eu\n" + text
    return text if text.endswith("\n") else text + "\n"


def failing_step_from_log(solve_log: str) -> str | None:
    """Requirement id of the step that was running when solve.sh stopped (last marker in the log)."""
    last: str | None = None
    for line in solve_log.splitlines():
        line = line.strip()
        if line.startswith(STEP_MARKER):
            last = line[len(STEP_MARKER):].strip()
        elif line == "[solve] done":
            return None
    return last
