"""Stage 4: task/environment (Dockerfile + clean repo copy) and task/tests/test.sh."""
from __future__ import annotations

import shutil
from pathlib import Path

from harness.localization.code_retriever import DEFAULT_IGNORED_DIRS, ProjectTree
from harness.providers.base import IEnvironmentBuilder, StackProfile

_VERIFIER_SRC = Path(__file__).with_name("verifier_template.py")

_DOCKERFILE = """\
# Generated by benchmark-harness. Offline at runtime: everything is installed at build time.
FROM python:{python_version}-slim-bookworm

ENV PYTHONDONTWRITEBYTECODE=1 \\
    PYTHONUNBUFFERED=1 \\
    PIP_NO_CACHE_DIR=1 \\
    PIP_DISABLE_PIP_VERSION_CHECK=1 \\
    DEBIAN_FRONTEND=noninteractive

RUN echo 'Acquire::Retries "5"; Acquire::http::Timeout "30";' > /etc/apt/apt.conf.d/80-retries \\
    && apt-get update \\
    && apt-get install -y --no-install-recommends build-essential git ca-certificates curl gnupg {apt_extra} \\
    && rm -rf /var/lib/apt/lists/*
{postgres_block}
WORKDIR /app/repo
COPY repo/ /app/repo/

RUN python -m pip install --upgrade pip \\
    && pip install "pytest>=8" {extra_packages} \\
{requirements_lines}    && true

ENV PYTHONPATH={pythonpath}
RUN mkdir -p /logs/verifier /tests /solution

CMD ["sh", "/tests/test.sh"]
"""

_POSTGRES_BLOCK = """
# PostgreSQL 16 from the PGDG repository with a ready cluster; started by test.sh at runtime.
RUN curl -fsSL --retry 5 https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor -o /usr/share/keyrings/pgdg.gpg \\
    && echo "deb [signed-by=/usr/share/keyrings/pgdg.gpg] http://apt.postgresql.org/pub/repos/apt bookworm-pgdg main" \\
       > /etc/apt/sources.list.d/pgdg.list \\
    && apt-get update \\
    && apt-get install -y --no-install-recommends postgresql-16 postgresql-contrib-16 libpq-dev \\
    && rm -rf /var/lib/apt/lists/* \\
    && service postgresql start \\
    && su postgres -c "psql -v ON_ERROR_STOP=1 -c \\"CREATE USER harness WITH SUPERUSER PASSWORD 'harness';\\"" \\
    && su postgres -c "createdb -O harness harness" \\
    && service postgresql stop
ENV HARNESS_POSTGRES=1 \\
    DATABASE_URL={db_url_scheme}://harness:harness@localhost:5432/harness \\
    PGHOST=localhost PGPORT=5432 PGUSER=harness PGPASSWORD=harness PGDATABASE=harness
"""

_TEST_SH = """\
#!/bin/sh
# Generated by benchmark-harness.
# Usage inside the sandbox: sh /tests/test.sh [all|fail_to_pass|pass_to_pass|anti_cheat]
# Writes /logs/verifier/{pytest.log,tests.xml,results.json,reward.txt}
set -u
CATEGORY="${1:-all}"
mkdir -p /logs/verifier
cd /app/repo || exit 2
export PYTHONDONTWRITEBYTECODE=1
export PYTHONPATH="{pythonpath}${PYTHONPATH:+:$PYTHONPATH}"
{postgres_start}
exec python /tests/verify.py --category "$CATEGORY" --manifest /tests/manifest.json \\
    --tests-dir /tests --logs-dir /logs/verifier --cwd /app/repo
"""

_POSTGRES_START = """\
if [ "${HARNESS_POSTGRES:-}" = "1" ]; then
  service postgresql start >/logs/verifier/postgres.log 2>&1
  i=0
  until pg_isready -q -h localhost || [ "$i" -ge 30 ]; do i=$((i+1)); sleep 1; done
  if [ -f alembic.ini ]; then
    alembic upgrade head >>/logs/verifier/postgres.log 2>&1 || echo "[test.sh] alembic upgrade head failed" >>/logs/verifier/postgres.log
  fi
  for seed in {seed_files}; do
    [ -f "$seed" ] && { psql -v ON_ERROR_STOP=1 -q -f "$seed" >>/logs/verifier/postgres.log 2>&1 || echo "[test.sh] seed $seed failed" >>/logs/verifier/postgres.log; }
  done
fi"""

_PYTEST_INI = "[pytest]\naddopts = -p no:cacheprovider\n"


def _ignore(ignored: set[str]):
    def _fn(_dir: str, names: list[str]) -> set[str]:
        return {n for n in names if n in ignored or n.endswith((".pyc", ".pyo"))}
    return _fn


def write_lf(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)


class PythonEnvironmentBuilder(IEnvironmentBuilder):
    def __init__(self, ignored_dirs=DEFAULT_IGNORED_DIRS) -> None:
        self.ignored = set(ignored_dirs)

    def copy_repo(self, repo: Path, dest: Path) -> None:
        if dest.exists():
            shutil.rmtree(dest)
        shutil.copytree(repo, dest, ignore=_ignore(self.ignored), symlinks=False)

    def render_dockerfile(self, profile: StackProfile, extra_packages: list[str]) -> str:
        req_lines = "".join(f"    && pip install -r {p} \\\n" for p in profile.requirements_files)
        if profile.installable:
            req_lines += "    && pip install -e . \\\n"
        pythonpath = ":".join(["/app/repo", *[f"/app/repo/{d}" for d in profile.package_dirs]])
        return _DOCKERFILE.format(
            python_version=profile.python_version,
            apt_extra="",
            postgres_block=_POSTGRES_BLOCK.replace("{db_url_scheme}", profile.db_url_scheme) if profile.uses_postgres else "",
            extra_packages=" ".join(f'"{p}"' for p in extra_packages),
            requirements_lines=req_lines,
            pythonpath=pythonpath,
        )

    def render_test_sh(self, profile: StackProfile) -> str:
        pythonpath = ":".join(["/app/repo", *[f"/app/repo/{d}" for d in profile.package_dirs]])
        seeds = " ".join(f'"{s}"' for s in profile.seed_files) or '""'
        postgres_start = _POSTGRES_START.replace("{seed_files}", seeds) if profile.uses_postgres else ""
        return _TEST_SH.replace("{pythonpath}", pythonpath).replace("{postgres_start}", postgres_start)

    def build(self, *, task_dir: Path, repo: Path, tree: ProjectTree, profile: StackProfile,
              extra_packages: list[str]) -> None:
        env_dir = task_dir / "environment"
        env_dir.mkdir(parents=True, exist_ok=True)
        if not (env_dir / "repo").exists():
            self.copy_repo(repo, env_dir / "repo")
        write_lf(env_dir / "Dockerfile", self.render_dockerfile(profile, extra_packages))
        write_lf(env_dir / ".dockerignore", "**/__pycache__\n**/*.pyc\n")
        tests_dir = task_dir / "tests"
        write_lf(tests_dir / "test.sh", self.render_test_sh(profile))
        write_lf(tests_dir / "pytest.ini", _PYTEST_INI)
        write_lf(tests_dir / "verify.py", _VERIFIER_SRC.read_text(encoding="utf-8"))
